---
name: AppDaemon_test
version: dev
slug: appdaemon_test
description: Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
url: https://github.com/hassio-addons/addon-appdaemon
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
ingress_port: 5050
# webui: http://[HOST]:[PORT:5050]
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
uart: true
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: AppDaemon_test
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  system_packages: []
  python_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  init_commands:
    - str
